version: '3.8'

services:
  adonis-mysql:
    image: mysql:5.7
    restart: always
    container_name: adonis-mysql
    healthcheck:
      test: ["CMD", "curl", "-fk", "tcp://localhost:3306"]
      interval: 300s
      timeout: 400s
      retries: 10
    ports:
      - 3306:3306
    expose:
      - "3306"
    volumes:
      - .mysql-data:/var/lib/mysql
    environment:
      MYSQL_USER: 'adonis'
      MYSQL_PASSWORD: 'adonis'
      MYSQL_DATABASE: 'adonis'
      MYSQL_ROOT_PASSWORD: 'root'
